# Generated by Django 4.2 on 2023-04-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0002_alter_userprofile_phone_number_employeeprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="EmployeeProfile",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
