# Generated by Django 4.2 on 2023-04-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mif", "0005_remove_userprofile_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("is_staff", models.BooleanField(default=True)),
                ("position", models.CharField(max_length=150)),
                (
                    "passport",
                    models.FileField(upload_to="employee_documents/passports/"),
                ),
                (
                    "employment_record",
                    models.FileField(
                        upload_to="employee_documents/employment_records/"
                    ),
                ),
                (
                    "state_pension_insurance_policy",
                    models.FileField(upload_to="employee_documents/spi_policies/"),
                ),
                (
                    "taxpayer_identification_code",
                    models.FileField(upload_to="employee_documents/ti_codes/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
