# Generated by Django 4.2 on 2023-04-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mif", "0006_employeeprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="employee",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
