# Generated by Django 4.2 on 2023-04-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0007_remove_employeeprofile_user_employeeprofile_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="share",
            field=models.FloatField(null=True),
        ),
    ]
