# Generated by Django 4.2 on 2023-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0008_userprofile_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_asset_value", models.FloatField(null=True)),
            ],
        ),
    ]
