# Generated by Django 4.2 on 2023-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0009_findistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="findistribution",
            name="current_value_share",
            field=models.FloatField(null=True),
        ),
    ]
