# Generated by Django 4.2 on 2023-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0013_depository"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherExpenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_expense", models.CharField(max_length=300, null=True)),
                ("amount_spent", models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="depository",
            old_name="number_of_shares",
            new_name="number_shares",
        ),
        migrations.AlterField(
            model_name="depository",
            name="status",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
