# Generated by Django 4.2 on 2023-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0014_otherexpenses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_income", models.CharField(max_length=300, null=True)),
                ("amount_received", models.FloatField(null=True)),
            ],
        ),
    ]
