# Generated by Django 4.2 on 2023-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0015_otherincome"),
    ]

    operations = [
        migrations.AddField(
            model_name="findistribution",
            name="budget",
            field=models.FloatField(null=True),
        ),
    ]
