# Generated by Django 4.2 on 2023-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0016_findistribution_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="depository",
            name="amount",
            field=models.FloatField(null=True),
        ),
    ]
