# Generated by Django 4.2 on 2023-04-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0017_depository_amount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Depository",
            new_name="DepositoryInstance",
        ),
        migrations.RenameModel(
            old_name="OtherExpenses",
            new_name="OtherExpense",
        ),
    ]
