# Generated by Django 4.2 on 2023-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0018_rename_depository_depositoryinstance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherexpense",
            name="amount_spent",
            field=models.FloatField(default=0, null=True),
        ),
    ]
