# Generated by Django 4.2 on 2023-04-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0019_alter_otherexpense_amount_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositoryinstance",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
