# Generated by Django 4.2 on 2023-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0020_alter_depositoryinstance_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositoryinstance",
            name="datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="otherexpense",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="otherincome",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
