# Generated by Django 4.2 on 2023-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0021_depositoryinstance_datetime_otherexpense_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositoryinstance",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="otherexpense",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="otherincome",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
