# Generated by Django 4.2 on 2023-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0023_employeeprofile_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_balance",
            field=models.FloatField(null=True),
        ),
    ]
