# Generated by Django 4.2 on 2023-04-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0026_employeeprofile_bank_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bank_card_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="share",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
