# Generated by Django 4.2 on 2023-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0027_userprofile_bank_card_number_alter_userprofile_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee", models.CharField(max_length=150, null=True)),
                ("report", models.FileField(upload_to="records/")),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
    ]
