# Generated by Django 4.2 on 2023-05-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0028_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnaliticsPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obj", models.CharField(max_length=300, null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                ("date", models.DateTimeField(null=True)),
            ],
        ),
    ]
