# Generated by Django 4.2 on 2023-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0029_analiticsplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="analiticsplan",
            name="quantity",
            field=models.FloatField(null=True),
        ),
    ]
