# Generated by Django 4.2 on 2023-05-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0031_rename_analiticsplan_analyticalplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyticalplan",
            old_name="obj",
            new_name="name_obj",
        ),
    ]
