# Generated by Django 4.2 on 2023-05-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0032_rename_obj_analyticalplan_name_obj"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyticalplan",
            old_name="date",
            new_name="datetime",
        ),
    ]
