# Generated by Django 4.2 on 2023-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0034_alter_analyticalplan_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticalplan",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
