# Generated by Django 4.2 on 2023-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0035_analyticalplan_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticalplan",
            name="token",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
