# Generated by Django 4.2 on 2023-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0039_alter_userprofile_current_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="current_balance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
