# Generated by Django 4.2 on 2023-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0040_alter_userprofile_current_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="findistribution",
            name="all_shares",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="findistribution",
            name="shares_left",
            field=models.IntegerField(null=True),
        ),
    ]
