# Generated by Django 4.2 on 2023-05-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0042_userprofile_is_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="opened_personal_account",
            field=models.BooleanField(default=False),
        ),
    ]
