# Generated by Django 4.2 on 2023-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0044_userprofile_recent_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositoryinstance",
            name="percentage_total",
            field=models.FloatField(null=True),
        ),
    ]
