# Generated by Django 4.2 on 2023-05-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0045_depositoryinstance_percentage_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="depositoryinstance",
            old_name="percentage_total",
            new_name="share_in_portfolio",
        ),
    ]
