# Generated by Django 4.2 on 2023-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0046_rename_percentage_total_depositoryinstance_share_in_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_company", models.CharField(max_length=500, null=True)),
                ("share_price", models.FloatField(null=True)),
                ("number_shares", models.IntegerField(null=True)),
                ("share_in_portfolio", models.FloatField(null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                ("amount", models.FloatField(null=True)),
                ("datetime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="depositoryinstance",
            old_name="join_stock_company",
            new_name="stock_company",
        ),
    ]
