# Generated by Django 4.2 on 2023-05-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0047_stockstorage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockstorage",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="stockstorage",
            name="status",
        ),
    ]
