# Generated by Django 4.2 on 2023-05-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0049_remove_stockstorage_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depositoryinstance",
            name="share_in_portfolio",
        ),
    ]
