# Generated by Django 4.2 on 2023-05-08 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mif", "0050_remove_depositoryinstance_share_in_portfolio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockstorage",
            name="share_price",
        ),
    ]
